### PR TITLE
Implement lens examples 

### PR DESCRIPTION
**Pull request by fogfish**
__WHY__

Improve documentation and tutorials

__WHAT__
* improve lens transformers `lens:map/3` instead of `lens:apply/3`
* examples application

### CODE REVIEW

**Comment by hachreak** [comment]
👍 
I started using this library some day ago and I need more example to understand how use it!
Thanks a lot! 😄 

One question: lens can work also with maps? Or they are made for records?

**Comment by fogfish** [comment]
They works with anything. 

Here is a quick cheatsheet:
* maps `lens:at(Key)`
* records `lens:ti(#myrec.myfield)`
* tuples `lens:t1()`, `lens:ti(N)`
* list of pairs `[{a, b}]` `lens:pair(Key)`
* list of tuples (keylists in Erlang notation) `lens:keylist(Key, N)`

Thank you for comments! I am going to work with documentation of the project and will add examples. As soon as I can.

**Comment by hachreak** [comment]
Thank you for you work! :D 
I hope to use your library more and more in future because it looks like they help to write aesthetically nice code and I love it!
(for now I started using the `either` XD)

**Comment by fogfish** [comment]
Just for you info. I am running production code with this lib. This is not an academical beast for me.

**Pull request merged**
